### ISSUE TITLE
Vala/TS for GJS example?

### ISSUE THREAD

**Issue by C-Loftus** [infapi00/at-spi2-examples#15]
I was wondering if you have any idea if there is any atspi sample code for Vala or GJS with Typescript anywhere that could be integrated into this repo. I have been looking around and can't seem to find either. I feel that there is a pretty big unmet need to have atspi bindings in a higher level statically typed language. I have not been able to figure out a setup for either of these since neither have any examples online from what I can see and both have build processes that aren't super straightforward.

**Comment by infapi00** [comment]
> I was wondering if you have any idea if there is any atspi sample code for Vala or GJS with Typescript anywhere 

No sorry, I personally don't have any idea of any sample using those languages. Sorry.

> I have not been able to figure out a setup for either of these since neither have any examples online from what I can see and both have build processes that aren't super straightforward.

If gobject-instrospection is able to generate bindings for those languages, I guess that it would be possible to set up something similar to python-atspi.

**Comment by C-Loftus** [comment]
Ok closing in favor of PR
